from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from tcl_lsp import meta, meta_tools

_METADATA_HEADER = (
    '# Generated by tcl-meta build-file.\n'
    '# Contains commands discovered from the active tool Tcl environment.\n'
    'meta module Tcl\n'
    '\n'
)


def test_meta_tools_reexports_meta_helpers() -> None:
    assert meta_tools.main is meta.main
    assert meta_tools.bundled_tcl_meta_path is meta.bundled_tcl_meta_path


def _build_metadata_with_tcl(tmp_path: Path, source_text: str) -> str:
    tclsh_path = shutil.which('tclsh')
    if tclsh_path is None:
        pytest.skip('tclsh is required for bundled Tcl helper tests')

    output_path = tmp_path / 'tool.meta.tcl'
    script_path = tmp_path / 'script.tcl'
    script_path.write_text(
        f'source [lindex $argv 0]\n{source_text}\ntcl-meta build-file [lindex $argv 1]\n',
        encoding='utf-8',
    )

    completed = subprocess.run(
        [
            tclsh_path,
            str(script_path),
            str(meta.bundled_tcl_meta_path()),
            str(output_path),
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0
    assert completed.stderr == ''
    return output_path.read_text(encoding='utf-8')


def test_helper_path_prints_existing_bundled_script(capsys: pytest.CaptureFixture[str]) -> None:
    result = meta.main(['helper-path'])

    captured = capsys.readouterr()
    helper_path = Path(captured.out.strip())

    assert result == 0
    assert helper_path == meta.bundled_tcl_meta_path().resolve(strict=False)
    assert helper_path.is_file()


def test_build_file_dispatches_to_bundled_tcl_helper(monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[list[str]] = []

    def fake_which(name: str) -> str | None:
        assert name == 'tclsh'
        return '/usr/bin/tclsh'

    def fake_run(command: list[str], check: bool) -> subprocess.CompletedProcess[str]:
        calls.append(command)
        assert check is False
        return subprocess.CompletedProcess(command, 0)

    monkeypatch.setattr(shutil, 'which', fake_which)
    monkeypatch.setattr(subprocess, 'run', fake_run)

    output_path = Path('/tmp/generated.meta.tcl')
    result = meta.main(['build-file', str(output_path)])

    assert result == 0
    assert calls == [
        ['/usr/bin/tclsh', str(meta.bundled_tcl_meta_path()), 'build-file', str(output_path)]
    ]


def test_bundled_tcl_helper_generates_metadata(tmp_path: Path) -> None:
    tclsh_path = shutil.which('tclsh')
    if tclsh_path is None:
        pytest.skip('tclsh is required for bundled Tcl helper tests')

    output_path = tmp_path / 'tool.meta.tcl'

    completed = subprocess.run(
        [
            tclsh_path,
            str(meta.bundled_tcl_meta_path()),
            'build-file',
            str(output_path),
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0
    assert completed.stderr == ''
    assert output_path.read_text(encoding='utf-8') == _METADATA_HEADER


def test_bundled_tcl_helper_derives_proc_signatures(tmp_path: Path) -> None:
    metadata = _build_metadata_with_tcl(tmp_path, 'proc demo {name {title friend} args} {}')

    assert metadata == _METADATA_HEADER + 'meta command demo {name ? title ? args}\n'


def test_bundled_tcl_helper_keeps_generic_signatures_for_non_proc_commands(
    tmp_path: Path,
) -> None:
    metadata = _build_metadata_with_tcl(tmp_path, 'interp alias {} aliasList {} list')

    assert metadata == _METADATA_HEADER + 'meta command aliasList args\n'


def test_bundled_tcl_helper_uses_proc_signature_when_subcommands_are_discovered(
    tmp_path: Path,
) -> None:
    metadata = _build_metadata_with_tcl(
        tmp_path,
        '\n'.join(
            (
                'proc widget {mode args} {',
                '    if {$mode eq "cget" || $mode eq "configure"} {',
                '        error "leaf"',
                '    }',
                '    error "bad option \\"$mode\\": must be cget or configure"',
                '}',
            )
        ),
    )

    assert metadata == (
        _METADATA_HEADER
        + 'meta command widget {mode args} {\n'
        + '    subcommand cget {args}\n'
        + '    subcommand configure {args}\n'
        + '}\n'
    )
