from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from tcl_lsp import meta_tools


def test_helper_path_prints_existing_bundled_script(capsys: pytest.CaptureFixture[str]) -> None:
    result = meta_tools.main(['helper-path'])

    captured = capsys.readouterr()
    helper_path = Path(captured.out.strip())

    assert result == 0
    assert helper_path == meta_tools.bundled_tcl_meta_path().resolve(strict=False)
    assert helper_path.is_file()


def test_build_file_dispatches_to_bundled_tcl_helper(monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[list[str]] = []

    def fake_which(name: str) -> str | None:
        assert name == 'tclsh'
        return '/usr/bin/tclsh'

    def fake_run(command: list[str], check: bool) -> subprocess.CompletedProcess[str]:
        calls.append(command)
        assert check is False
        return subprocess.CompletedProcess(command, 0)

    monkeypatch.setattr(shutil, 'which', fake_which)
    monkeypatch.setattr(subprocess, 'run', fake_run)

    output_path = Path('/tmp/generated.meta.tcl')
    result = meta_tools.main(['build-file', str(output_path)])

    assert result == 0
    assert calls == [
        ['/usr/bin/tclsh', str(meta_tools.bundled_tcl_meta_path()), 'build-file', str(output_path)]
    ]


def test_bundled_tcl_helper_generates_metadata(tmp_path: Path) -> None:
    tclsh_path = shutil.which('tclsh')
    if tclsh_path is None:
        pytest.skip('tclsh is required for bundled Tcl helper tests')

    output_path = tmp_path / 'tool.meta.tcl'

    completed = subprocess.run(
        [
            tclsh_path,
            str(meta_tools.bundled_tcl_meta_path()),
            'build-file',
            str(output_path),
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0
    assert completed.stderr == ''
    assert output_path.read_text(encoding='utf-8') == (
        '# Generated by tcl-meta build-file.\n'
        '# Contains commands discovered from the active tool Tcl environment.\n'
        'meta module Tcl\n'
        '\n'
    )
